# Generated by Django 2.2.4 on 2019-08-18 16:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('excuseapi', '0002_excuse_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excuse',
            name='reason',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('work', 'work'), ('plans', 'plans'), ('myself', 'myself'), ('none', 'none')], max_length=22),
        ),
    ]
