# Generated by Django 2.2.4 on 2019-08-18 16:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('excuseapi', '0003_auto_20190818_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excuse',
            name='reason',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('work', 'work'), ('plans', 'plans'), ('myself', 'myself')], max_length=17),
        ),
    ]
